// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieStoreProject.DataAccess;

namespace MovieStoreProject.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("ActorId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("ActorMovie");
                });

            modelBuilder.Entity("CustomerMovie", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("CustomerMovie");
                });

            modelBuilder.Entity("MovieStoreProject.Entities.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActorSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActorId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            ActorName = "Actor1",
                            ActorSurname = "ActorSurname1"
                        },
                        new
                        {
                            ActorId = 2,
                            ActorName = "Actor2",
                            ActorSurname = "ActorSurname2"
                        },
                        new
                        {
                            ActorId = 3,
                            ActorName = "Actor3",
                            ActorSurname = "ActorSurname3"
                        },
                        new
                        {
                            ActorId = 4,
                            ActorName = "Actor4",
                            ActorSurname = "ActorSurname4"
                        },
                        new
                        {
                            ActorId = 5,
                            ActorName = "Actor5",
                            ActorSurname = "ActorSurname5"
                        },
                        new
                        {
                            ActorId = 6,
                            ActorName = "Actor6",
                            ActorSurname = "ActorSurname6"
                        });
                });

            modelBuilder.Entity("MovieStoreProject.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FavouriteCategories")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerName = "Customer1",
                            CustomerSurname = "CustomerSurname1",
                            FavouriteCategories = 2
                        },
                        new
                        {
                            CustomerId = 2,
                            CustomerName = "Customer2",
                            CustomerSurname = "CustomerSurname2",
                            FavouriteCategories = 4
                        },
                        new
                        {
                            CustomerId = 3,
                            CustomerName = "Customer3",
                            CustomerSurname = "CustomerSurname3",
                            FavouriteCategories = 3
                        },
                        new
                        {
                            CustomerId = 4,
                            CustomerName = "Customer4",
                            CustomerSurname = "CustomerSurname4",
                            FavouriteCategories = 2
                        },
                        new
                        {
                            CustomerId = 5,
                            CustomerName = "Customer5",
                            CustomerSurname = "CustomerSurname5",
                            FavouriteCategories = 1
                        },
                        new
                        {
                            CustomerId = 6,
                            CustomerName = "Customer6",
                            CustomerSurname = "CustomerSurname6",
                            FavouriteCategories = 1
                        });
                });

            modelBuilder.Entity("MovieStoreProject.Entities.Director", b =>
                {
                    b.Property<int>("DirectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DirectorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectorSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DirectorId");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            DirectorId = 1,
                            DirectorName = "Director1",
                            DirectorSurname = "DirectorSurname2"
                        },
                        new
                        {
                            DirectorId = 2,
                            DirectorName = "Director2",
                            DirectorSurname = "DirectorSurname3"
                        },
                        new
                        {
                            DirectorId = 3,
                            DirectorName = "Director3",
                            DirectorSurname = "DirectorSurname3"
                        },
                        new
                        {
                            DirectorId = 4,
                            DirectorName = "Director4",
                            DirectorSurname = "DirectorSurname4"
                        },
                        new
                        {
                            DirectorId = 5,
                            DirectorName = "Director5",
                            DirectorSurname = "DirectorSurname5"
                        },
                        new
                        {
                            DirectorId = 6,
                            DirectorName = "Director6",
                            DirectorSurname = "DirectorSurname6"
                        });
                });

            modelBuilder.Entity("MovieStoreProject.Entities.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("MovieCategory")
                        .HasColumnType("int");

                    b.Property<string>("MovieName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MovieYear")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MovieId");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            DirectorId = 1,
                            MovieCategory = 2,
                            MovieName = "Movie1",
                            MovieYear = new DateTime(2022, 6, 17, 17, 21, 25, 18, DateTimeKind.Local).AddTicks(1726),
                            Price = 1500m
                        },
                        new
                        {
                            MovieId = 2,
                            DirectorId = 2,
                            MovieCategory = 3,
                            MovieName = "Movie2",
                            MovieYear = new DateTime(2022, 6, 17, 17, 21, 25, 18, DateTimeKind.Local).AddTicks(8674),
                            Price = 1502m
                        },
                        new
                        {
                            MovieId = 3,
                            DirectorId = 1,
                            MovieCategory = 1,
                            MovieName = "Movie3",
                            MovieYear = new DateTime(2022, 6, 17, 17, 21, 25, 18, DateTimeKind.Local).AddTicks(8687),
                            Price = 1000m
                        },
                        new
                        {
                            MovieId = 4,
                            DirectorId = 4,
                            MovieCategory = 2,
                            MovieName = "Movie4",
                            MovieYear = new DateTime(2022, 6, 17, 17, 21, 25, 18, DateTimeKind.Local).AddTicks(8689),
                            Price = 100m
                        },
                        new
                        {
                            MovieId = 5,
                            DirectorId = 3,
                            MovieCategory = 4,
                            MovieName = "Movie5",
                            MovieYear = new DateTime(2022, 6, 17, 17, 21, 25, 18, DateTimeKind.Local).AddTicks(8690),
                            Price = 350m
                        },
                        new
                        {
                            MovieId = 6,
                            DirectorId = 5,
                            MovieCategory = 3,
                            MovieName = "Movie6",
                            MovieYear = new DateTime(2022, 6, 17, 17, 21, 25, 18, DateTimeKind.Local).AddTicks(8691),
                            Price = 500m
                        },
                        new
                        {
                            MovieId = 7,
                            DirectorId = 6,
                            MovieCategory = 4,
                            MovieName = "Movie7",
                            MovieYear = new DateTime(2022, 6, 17, 17, 21, 25, 18, DateTimeKind.Local).AddTicks(8693),
                            Price = 700m
                        },
                        new
                        {
                            MovieId = 8,
                            DirectorId = 6,
                            MovieCategory = 1,
                            MovieName = "Movie8",
                            MovieYear = new DateTime(2022, 6, 17, 17, 21, 25, 18, DateTimeKind.Local).AddTicks(8694),
                            Price = 850m
                        });
                });

            modelBuilder.Entity("MovieStoreProject.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MovieId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            MovieId = 2,
                            Price = 2000m,
                            PurchaseDate = new DateTime(2022, 6, 17, 17, 21, 25, 19, DateTimeKind.Local).AddTicks(3114)
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 3,
                            MovieId = 3,
                            Price = 1000m,
                            PurchaseDate = new DateTime(2022, 6, 17, 17, 21, 25, 19, DateTimeKind.Local).AddTicks(3342)
                        },
                        new
                        {
                            OrderId = 3,
                            CustomerId = 6,
                            MovieId = 4,
                            Price = 2000m,
                            PurchaseDate = new DateTime(2022, 6, 17, 17, 21, 25, 19, DateTimeKind.Local).AddTicks(3346)
                        },
                        new
                        {
                            OrderId = 4,
                            CustomerId = 5,
                            MovieId = 7,
                            Price = 2000m,
                            PurchaseDate = new DateTime(2022, 6, 17, 17, 21, 25, 19, DateTimeKind.Local).AddTicks(3347)
                        },
                        new
                        {
                            OrderId = 5,
                            CustomerId = 3,
                            MovieId = 7,
                            Price = 2000m,
                            PurchaseDate = new DateTime(2022, 6, 17, 17, 21, 25, 19, DateTimeKind.Local).AddTicks(3348)
                        },
                        new
                        {
                            OrderId = 6,
                            CustomerId = 2,
                            MovieId = 5,
                            Price = 2000m,
                            PurchaseDate = new DateTime(2022, 6, 17, 17, 21, 25, 19, DateTimeKind.Local).AddTicks(3349)
                        },
                        new
                        {
                            OrderId = 7,
                            CustomerId = 3,
                            MovieId = 2,
                            Price = 2000m,
                            PurchaseDate = new DateTime(2022, 6, 17, 17, 21, 25, 19, DateTimeKind.Local).AddTicks(3350)
                        });
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.HasOne("MovieStoreProject.Entities.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieStoreProject.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerMovie", b =>
                {
                    b.HasOne("MovieStoreProject.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieStoreProject.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieStoreProject.Entities.Movie", b =>
                {
                    b.HasOne("MovieStoreProject.Entities.Director", "Director")
                        .WithMany("Movie")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("MovieStoreProject.Entities.Order", b =>
                {
                    b.HasOne("MovieStoreProject.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieStoreProject.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieStoreProject.Entities.Director", b =>
                {
                    b.Navigation("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
